### ISSUE TITLE
`Return value is used for API consistency.`

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#133]
`Return value is used for API consistency.`

Let's use the language-specific keyword to denote we don't return anything, `void`. While it may be pleasing to the eye, an API is not made consistent by applying the same pattern everywhere. If we don't need to use a return value here, let's not have one.

_Originally posted by @bmagyar in https://github.com/ros-controls/ros2_control/pull/121/review_comment/create_

**Comment by bmagyar** [comment]
@v-lopez what is your opinion on this?

**Comment by v-lopez** [comment]
IMO go with `void` in this particular case.

And in general, we can have the same return type everywhere, and the caller's job is to check for OK or ERROR. but I guess that if we're not using `bool` is because in the future we may need a 3rd return value? 

In that case, when we add a 3rd value, won't all callers need to update their return value checking to take into account the new value? This is all kinds of troublesome, I'd rather break API to make sure the new values are taken into account.

**Comment by bmagyar** [comment]
The original post was focusing on not having a return type when one is not warranted

**Comment by v-lopez** [comment]
Yeah, as I said I'd go with `void` in this case. 
But in general I don't fully agree with having a standard `return_type` for everything, even for functions that are supposed to return something.
