### ISSUE TITLE
API docs link gives 404

### ISSUE THREAD

**Issue by lorepieri8** [ros-controls/ros2_control#510]
**Describe the bug**

API docs link gives 404

**To Reproduce**

https://ros-controls.github.io/control.ros.org/ros2_control/doc/index.html
Click on "here"

**Expected behavior**

**Comment by bmagyar** [comment]
thanks, we are aware of this. Didn't get to fix the deployment script yuet

**Comment by jaron-l** [comment]
Looks like I messed up the link on the API documentation page to the doxygen sub-path and it needs the extra controls.ros.org sub-folder path. So it should point to something like https://ros-controls.github.io/control.ros.org/api/index.html instead of https://ros-controls.github.io/api/index.html which doesn't exist. I'm going to investigate this a little more to find something that will hopefully work with both the local build and the dynamic one that GitHub pages makes.
